# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Group.create([
  { :name => "A" },
  { :name => "B" },
  { :name => "C" },
  { :name => "D" },
  { :name => "E" },
  { :name => "F" },
  { :name => "G" },
  { :name => "H" }
], :without_protection => true )



Match.create([
  { :stage => "G", :venue_id => 12, :team1_id => 1, :team2_id => 2, :kickoff => "2014-06-12 17:00:00" },
  { :stage => "G", :venue_id => 7, :team1_id => 3, :team2_id => 4, :kickoff => "2014-06-13 13:00:00" },
  { :stage => "G", :venue_id => 11, :team1_id => 5, :team2_id => 6, :kickoff => "2014-06-13 16:00:00" },
  { :stage => "G", :venue_id => 3, :team1_id => 7, :team2_id => 8, :kickoff => "2014-06-13 18:00:00" },
  { :stage => "G", :venue_id => 1, :team1_id => 9, :team2_id => 10, :kickoff => "2014-06-14 13:00:00" },
  { :stage => "G", :venue_id => 9, :team1_id => 11, :team2_id => 12, :kickoff => "2014-06-14 22:00:00" },
  { :stage => "G", :venue_id => 5, :team1_id => 13, :team2_id => 14, :kickoff => "2014-06-14 16:00:00" },
  { :stage => "G", :venue_id => 6, :team1_id => 15, :team2_id => 16, :kickoff => "2014-06-14 18:00:00" },
  { :stage => "G", :venue_id => 2, :team1_id => 17, :team2_id => 18, :kickoff => "2014-06-15 13:00:00" },
  { :stage => "G", :venue_id => 8, :team1_id => 19, :team2_id => 20, :kickoff => "2014-06-15 16:00:00" },
  { :stage => "G", :venue_id => 10, :team1_id => 21, :team2_id => 22, :kickoff => "2014-06-15 19:00:00" },
  { :stage => "G", :venue_id => 4, :team1_id => 23, :team2_id => 24, :kickoff => "2014-06-16 16:00:00" },
  { :stage => "G", :venue_id => 11, :team1_id => 25, :team2_id => 26, :kickoff => "2014-06-16 13:00:00" },
  { :stage => "G", :venue_id => 7, :team1_id => 27, :team2_id => 28, :kickoff => "2014-06-16 19:00:00" },
  { :stage => "G", :venue_id => 1, :team1_id => 29, :team2_id => 30, :kickoff => "2014-06-17 13:00:00" },
  { :stage => "G", :venue_id => 3, :team1_id => 31, :team2_id => 32, :kickoff => "2014-06-17 18:00:00" },
  { :stage => "G", :venue_id => 5, :team1_id => 1, :team2_id => 3, :kickoff => "2014-06-17 16:00:00" },
  { :stage => "G", :venue_id => 6, :team1_id => 4, :team2_id => 2, :kickoff => "2014-06-18 18:00:00" },
  { :stage => "G", :venue_id => 10, :team1_id => 5, :team2_id => 7, :kickoff => "2014-06-18 16:00:00" },
  { :stage => "G", :venue_id => 8, :team1_id => 8, :team2_id => 6, :kickoff => "2014-06-18 13:00:00" },
  { :stage => "G", :venue_id => 2, :team1_id => 9, :team2_id => 11, :kickoff => "2014-06-19 13:00:00" },
  { :stage => "G", :venue_id => 7, :team1_id => 12, :team2_id => 10, :kickoff => "2014-06-19 19:00:00" },
  { :stage => "G", :venue_id => 12, :team1_id => 13, :team2_id => 15, :kickoff => "2014-06-19 16:00:00" },
  { :stage => "G", :venue_id => 9, :team1_id => 16, :team2_id => 14, :kickoff => "2014-06-20 13:00:00" },
  { :stage => "G", :venue_id => 11, :team1_id => 17, :team2_id => 19, :kickoff => "2014-06-20 16:00:00" },
  { :stage => "G", :venue_id => 4, :team1_id => 20, :team2_id => 18, :kickoff => "2014-06-20 19:00:00" },
  { :stage => "G", :venue_id => 1, :team1_id => 21, :team2_id => 23, :kickoff => "2014-06-21 13:00:00" },
  { :stage => "G", :venue_id => 3, :team1_id => 24, :team2_id => 22, :kickoff => "2014-06-21 18:00:00" },
  { :stage => "G", :venue_id => 5, :team1_id => 25, :team2_id => 27, :kickoff => "2014-06-21 16:00:00" },
  { :stage => "G", :venue_id => 6, :team1_id => 28, :team2_id => 26, :kickoff => "2014-06-22 18:00:00" },
  { :stage => "G", :venue_id => 10, :team1_id => 29, :team2_id => 31, :kickoff => "2014-06-22 13:00:00" },
  { :stage => "G", :venue_id => 8, :team1_id => 32, :team2_id => 30, :kickoff => "2014-06-22 16:00:00" },
  { :stage => "G", :venue_id => 2, :team1_id => 4, :team2_id => 1, :kickoff => "2014-06-23 17:00:00" },
  { :stage => "G", :venue_id => 9, :team1_id => 2, :team2_id => 3, :kickoff => "2014-06-23 17:00:00" },
  { :stage => "G", :venue_id => 4, :team1_id => 8, :team2_id => 5, :kickoff => "2014-06-23 13:00:00" },
  { :stage => "G", :venue_id => 12, :team1_id => 6, :team2_id => 7, :kickoff => "2014-06-23 13:00:00" },
  { :stage => "G", :venue_id => 3, :team1_id => 12, :team2_id => 9, :kickoff => "2014-06-24 16:00:00" },
  { :stage => "G", :venue_id => 5, :team1_id => 10, :team2_id => 11, :kickoff => "2014-06-24 16:00:00" },
  { :stage => "G", :venue_id => 7, :team1_id => 16, :team2_id => 13, :kickoff => "2014-06-24 13:00:00" },
  { :stage => "G", :venue_id => 1, :team1_id => 14, :team2_id => 15, :kickoff => "2014-06-24 13:00:00" },
  { :stage => "G", :venue_id => 6, :team1_id => 20, :team2_id => 17, :kickoff => "2014-06-25 16:00:00" },
  { :stage => "G", :venue_id => 10, :team1_id => 18, :team2_id => 19, :kickoff => "2014-06-25 17:00:00" },
  { :stage => "G", :venue_id => 8, :team1_id => 24, :team2_id => 21, :kickoff => "2014-06-25 13:00:00" },
  { :stage => "G", :venue_id => 11, :team1_id => 22, :team2_id => 23, :kickoff => "2014-06-25 13:00:00" },
  { :stage => "G", :venue_id => 9, :team1_id => 28, :team2_id => 25, :kickoff => "2014-06-26 13:00:00" },
  { :stage => "G", :venue_id => 2, :team1_id => 26, :team2_id => 27, :kickoff => "2014-06-26 13:00:00" },
  { :stage => "G", :venue_id => 12, :team1_id => 32, :team2_id => 29, :kickoff => "2014-06-26 17:00:00" },
  { :stage => "G", :venue_id => 4, :team1_id => 30, :team2_id => 31, :kickoff => "2014-06-26 17:00:00" },
  { :stage => "16", :venue_id => 1, :team1_id => nil, :team2_id => nil, :kickoff => "2014-06-28 13:00:00" },
  { :stage => "16", :venue_id => 10, :team1_id => nil, :team2_id => nil, :kickoff => "2014-06-28 17:00:00" },
  { :stage => "16", :venue_id => 5, :team1_id => nil, :team2_id => nil, :kickoff => "2014-06-29 13:00:00" },
  { :stage => "16", :venue_id => 9, :team1_id => nil, :team2_id => nil, :kickoff => "2014-06-29 17:00:00" },
  { :stage => "16", :venue_id => 2, :team1_id => nil, :team2_id => nil, :kickoff => "2014-06-30 13:00:00" },
  { :stage => "16", :venue_id => 8, :team1_id => nil, :team2_id => nil, :kickoff => "2014-06-30 17:00:00" },
  { :stage => "16", :venue_id => 12, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-01 13:00:00" },
  { :stage => "16", :venue_id => 11, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-01 17:00:00" },
  { :stage => "QF", :venue_id => 5, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-04 17:00:00" },
  { :stage => "QF", :venue_id => 10, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-04 13:00:00" },
  { :stage => "QF", :venue_id => 11, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-05 17:00:00" },
  { :stage => "QF", :venue_id => 2, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-05 13:00:00" },
  { :stage => "SF", :venue_id => 1, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-08 17:00:00" },
  { :stage => "SF", :venue_id => 12, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-09 17:00:00" },
  { :stage => "3", :venue_id => 2, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-12 17:00:00" },
  { :stage => "F", :venue_id => 10, :team1_id => nil, :team2_id => nil, :kickoff => "2014-07-13 17:00:00" }
], :without_protection => true )



Team.create([
  { :group_id => 1, :code => "BRA", :name => "Brazil" },
  { :group_id => 1, :code => "HRV", :name => "Croatia" },
  { :group_id => 1, :code => "MEX", :name => "Mexico" },
  { :group_id => 1, :code => "CMR", :name => "Cameroon" },
  { :group_id => 2, :code => "ESP", :name => "Spain" },
  { :group_id => 2, :code => "NLD", :name => "Netherlands" },
  { :group_id => 2, :code => "CHL", :name => "Chile" },
  { :group_id => 2, :code => "AUS", :name => "Australia" },
  { :group_id => 3, :code => "COL", :name => "Colombia" },
  { :group_id => 3, :code => "GRC", :name => "Greece" },
  { :group_id => 3, :code => "CIV", :name => "Ivory Coast" },
  { :group_id => 3, :code => "JPN", :name => "Japan" },
  { :group_id => 4, :code => "URY", :name => "Uruguay" },
  { :group_id => 4, :code => "CRC", :name => "Costa Rica" },
  { :group_id => 4, :code => "ENG", :name => "England" },
  { :group_id => 4, :code => "ITA", :name => "Italy" },
  { :group_id => 5, :code => "CHE", :name => "Switzerland" },
  { :group_id => 5, :code => "ECU", :name => "Ecuador" },
  { :group_id => 5, :code => "FRA", :name => "France" },
  { :group_id => 5, :code => "HND", :name => "Honduras" },
  { :group_id => 6, :code => "ARG", :name => "Argentina" },
  { :group_id => 6, :code => "BIH", :name => "Bosnia and Herzegovina" },
  { :group_id => 6, :code => "IRN", :name => "Iran" },
  { :group_id => 6, :code => "NGA", :name => "Nigeria" },
  { :group_id => 7, :code => "DEU", :name => "Germany" },
  { :group_id => 7, :code => "PRT", :name => "Portugal" },
  { :group_id => 7, :code => "GHA", :name => "Ghana" },
  { :group_id => 7, :code => "USA", :name => "USA" },
  { :group_id => 8, :code => "BEL", :name => "Belgium" },
  { :group_id => 8, :code => "DZA", :name => "Algeria" },
  { :group_id => 8, :code => "RUS", :name => "Russia" },
  { :group_id => 8, :code => "KOR", :name => "Korea" }
], :without_protection => true )



Venue.create([
  { :name => "Estadio Mineirao", :city => "Belo Horizonte" },
  { :name => "Estadio Nacional", :city => "Brasilia" },
  { :name => "Arena Pantanal", :city => "Cuiaba" },
  { :name => "Arena da Baixada", :city => "Curitiba" },
  { :name => "Estadio Castelao", :city => "Fortaleza" },
  { :name => "Arena Amazonia", :city => "Manaus" },
  { :name => "Estadio das Dunas", :city => "Natal" },
  { :name => "Estadio Beira-Rio", :city => "Porto Alegre" },
  { :name => "Arena Pernambuco", :city => "Recife" },
  { :name => "Estadio do Maracana", :city => "Rio De Janeiro" },
  { :name => "Arena Fonte Nova", :city => "Salvador" },
  { :name => "Arena de Sao Paulo", :city => "Sao Paulo" }
], :without_protection => true )


